#ifndef __RADIOBERRY_IOCTL_H__
#define __RADIOBERRY_IOCTL_H__

#include <linux/types.h>
#include <linux/ioctl.h>

#define RADIOBERRY_MAGIC	('x')

#define RADIOBERRY_IOC_START_STREAM		_IOW(RADIOBERRY_MAGIC, 1, __u8)
#define RADIOBERRY_IOC_STOP_STREAM		_IOW(RADIOBERRY_MAGIC, 2, __u8)
#define RADIOBERRY_IOC_COMMAND_WRITE	_IOW(RADIOBERRY_MAGIC, 3, __u8)
#define RADIOBERRY_IOC_COMMAND_READ		_IOW(RADIOBERRY_MAGIC, 4, __u8)
#define RADIOBERRY_IOC_FREQ2			_IOW(RADIOBERRY_MAGIC, 5, __u8)
#define RADIOBERRY_IOC_FREQ3			_IOW(RADIOBERRY_MAGIC, 6, __u8)
#define RADIOBERRY_IOC_FREQ4			_IOW(RADIOBERRY_MAGIC, 7, __u8)

#endif
