set_global_assignment -name VERILOG_FILE rtl/ad9866.v
set_global_assignment -name VERILOG_FILE rtl/ddr_mux.v
set_global_assignment -name VERILOG_FILE rtl/radioberry.v
set_global_assignment -name VERILOG_FILE rtl/reset_handler.v
set_global_assignment -name VERILOG_FILE rtl/spi_slave.v
set_global_assignment -name VERILOG_FILE rtl/timescale.v
set_global_assignment -name VERILOG_FILE rtl/transmitter.v
set_global_assignment -name VERILOG_FILE rtl/rxstream.v

set_global_assignment -name VERILOG_FILE rtl/ethernet/arp.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/crc32.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/dhcp.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/ethernet.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/icmp.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/icmp_fifo.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/ip_recv.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/ip_send.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/mac_recv.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/mac_send.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/mdio.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/network.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/phy_cfg.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/phy_recv.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/phy_send.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/rmii_recv.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/rmii_send.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/udp_recv.v
set_global_assignment -name VERILOG_FILE rtl/ethernet/udp_send.v

set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/rx_iq_fifo.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/rxFIFO.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/txFIFO.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/counter.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/sqroot.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/square.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/ad9866pll.v
set_global_assignment -name VERILOG_FILE rtl/cyclone_ip/commandFIFO.v

set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/cic.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/CicInterpM5.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/cic_comb.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/cic_integrator.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/cordic.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/cpl_cordic.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firfilt.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/FirInterp8_1024.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firram36.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firram36I_1024.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/receiver.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/varcic.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/FirInterp5_1025_EER.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/FirInterp8_1024.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firram36.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firram36I_1024.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firram36I_205.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firrom1_1025.v


set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firrom/firromH.v
set_global_assignment -name VERILOG_FILE rtl/radio_openhpsdr/firrom/firromI_1024.v